### ISSUE TITLE
Gnome 40 session crashes if radio kept on until screen locks automatically

### ISSUE THREAD

**Issue by prasadpatil25** [hslbck/gnome-shell-extension-radio#177] opened 2021-06-04 16:00 UTC
This happens every time I left my radio on and system ideal. After 5 mins (my system lock time if ideal) the screen gets lock and then gnome crashes and the radio stops too.

I am using Fedora 34 (Gnome 40) on the Wayland session.

This is the Gnome crash error log:

https://retrace.fedoraproject.org/faf/reports/133047/

Let me know if I should provide more info to debug this issue.

**Comment by hslbck** [comment] 2021-06-06 18:35
I could not reproduce this issue with Archlinux GNOME 40 and Wayland. The extension gets disabled as expected. Are there any logs from journalctl with the info about "radio@hslbck" that the extension is causing this issue?

**Comment by snoopakon** [comment] 2021-06-21 09:39
@hslbck  I don't see any logs using journalctl relevant to radio@hslbck.

**Comment by hslbck** [comment] 2021-11-10 19:21
Closing as stacktrace and logs aren't connected with extension itself

**Closed by hslbck** 2021-11-10 19:21 UTC
