### ISSUE TITLE
Playback stops when screenn blanks

### ISSUE THREAD

**Issue by emulti** [hslbck/gnome-shell-extension-radio#141] opened 2020-03-06 07:59 UTC
Very nice extension!
I am using it on a Gnome Media Centre connected to a large screen
After a lot of  messing about to disable the inconvenient 'Lock Shield' on display timeout, (using the RemoveShield extension), and disabling DPMS so the display does not power off, I found that your extension still stops playback when the screen blanks.
Other audio programs don't do this, so it's not the network connection going to sleep. 
Is there a possibility to maintain playback from your extension after the 'idle delay' timeout expires and the screen blanks?

**Comment by hslbck** [comment] 2020-03-17 14:36
It seems to me that the lock screen or at least the extension handling by GNOME is called, because then the extensions gets disabled.
Did you try disabling lock screen in the GNOME settings?

**Comment by emulti** [comment] 2020-03-18 01:51
Yes, the lock screen is disabled (through the "Remove Shield" extension rather than gsettings, which didn't work for me).
After the timeout period, the screen except for the mouse cursor blanks. At that point, the extension stops playback.
I wonder if this is due to power saving policies which trigger at that point?
If I have other applications playing audio, they continue to play after the screen blanks, which suggests it is not the audio subsystem being shut down which stops extension playback.

**Comment by jeanmarie18** [comment] 2020-03-26 07:48
Hello,
I have the same problem here on my Ubuntu (extension installed from Software / Add-ons / Shell Extensions).
I was redirected here after my question+bug created on launchpad (https://bugs.launchpad.net/ubuntu/+bug/1868853).
It would be cool to correct this problem.

**Comment by axelsimon** [comment] 2020-09-22 09:53
Looks like a duplicate of #4. Maybe close this one?
[This comment](https://github.com/hslbck/gnome-shell-extension-radio/issues/4#issuecomment-528548342) even offers a workaround.

**Comment by hslbck** [comment] 2020-10-12 19:09
Closing issue as duplicate of #4. Please check mentioned workaround

**Closed** 2020-10-12 19:08 UTC
