### ISSUE TITLE
Latest version crash on gnome shell start

### ISSUE THREAD

**Issue by jorgemf** [hslbck/gnome-shell-extension-radio#33] opened 2016-10-14 15:50 UTC
Most of the times I log in into my account the extension is not loaded due an error. I have to uninstall and install it again to make it work.

I do not know how to take a look to the logs and report a better error report. Let me know how I can help to fix the issue.

**Comment by hslbck** [comment] 2016-10-18 14:34
Hi,

thanks for reporting. Can you provide me more info about your system in order to fix this issue.

Which Gnome Shell version do you use? Terminal command `gnome-shell --version`
Which distribution do you use?
Do you have further extensions installed besides Internet Radio?
Log info would be helpful. You can use the Gnome log application or terminal command `journalctl` for that. Type `journalctl | grep JS` will print out the JavaScript log. With `journalctl -f | grep JS` you follow the log.

BR

**Comment by jorgemf** [comment] 2016-10-18 18:30
Thanks, after one of the latest updates of the system it seems stable now, anyway here is the information:

GNOME Shell 3.22.1
Archlinux
Other extensions: AlternateTab, Applications Overview Tooltip, Battery Status, Bumblebee Indicator, Dash to Dock, Disable Workspace Switcher Popup, Freon, OpenWeather, Optirun, Pixel Saver, Show IP, Status Area Horizontal Spacing, system-monitor, TopIcons, Transparent OSD, windowNavigator

The only meanful message related in the logs:
```
Gjs-Message: JS LOG: Extension "radio@hslbck.gmail.com" had error: TypeError: radioMenu is undefined
Gjs-Message: JS LOG: Extension "radio@hslbck.gmail.com" had error: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SettingsDaemon was not provided by any .service files
```
Here is more context:
```
oct 13 15:05:09 asus28 org.gnome.Shell.desktop[932]: Gjs-Message: JS LOG: Ignored exception from dbus method: Gio.IOErrorEnum: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code19: Operation was cancelled
oct 13 15:05:09 asus28 org.gnome.Shell.desktop[932]: Gjs-Message: JS LOG: gnome-session gave us a dead inhibitor: /org/gnome/SessionManager/Inhibitor2
oct 13 15:06:10 asus28 gnome-shell[1017]: JS LOG: Failed to launch ibus-daemon: Failed to execute child process "ibus-daemon" (No such file or directory)
oct 13 15:06:10 asus28 gnome-shell[1017]: JS LOG: No permission to trigger offline updates: Polkit.Error: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Action org.freedesktop.packagekit.trigger-offline-update is not registered
oct 13 15:06:10 asus28 gnome-shell[1017]: JS LOG: System monitor applet init from /home/jorge/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com
oct 13 15:06:10 asus28 gnome-shell[1017]: JS LOG: System monitor applet enabling
oct 13 15:06:11 asus28 gnome-shell[1017]: JS LOG: System monitor applet enabling done
oct 13 15:06:11 asus28 gnome-shell[1017]: JS LOG: [pixel-saver]: 'appmenu' is not a valid button.
oct 13 15:06:11 asus28 gnome-shell[1017]: JS LOG: Extension "alternate-tab@gnome-shell-extensions.gcampax.github.com" had error: Error: second argument to Lang.bind() must be a function, not undefined
oct 13 15:06:11 asus28 gnome-shell[1017]: JS LOG: Extension "radio@hslbck.gmail.com" had error: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SettingsDaemon was not provided by any .service files
oct 13 15:06:11 asus28 gnome-shell[1017]: JS LOG: Extension system-monitor@paradoxxx.zero.gmail.com already installed in /home/jorge/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com. /usr/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com will not be loaded
oct 13 15:06:11 asus28 gnome-shell[1017]: JS LOG: Extension dash-to-dock@micxgx.gmail.com already installed in /home/jorge/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com. /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com will not be loaded
```

I forgot to say thanks for the extension. I am using it everyday and very happy with it.

**Comment by hslbck** [comment] 2016-10-19 14:23
ok, good to hear that the update did help.
I'll close the issue for now. If the issue keeps appearing, feel free to open it again

**Comment by jorgemf** [comment] 2016-10-23 17:13
@hslbck This is still happening. It is not happening when the option "Enable play/stop media keys" is off. But when it is on it is happening. I disabled the option and that is why I though the update on the system fixed it.
I cannot open the issue again.

**Comment by hslbck** [comment] 2016-11-02 16:10
ok I will look into. I'm not sure if I can reproduce it, because I can only emulate the media keys

**Comment by zapashcanon** [comment] 2016-11-28 22:25
@jorgemf, are you using Wayland ?

**Comment by jorgemf** [comment] 2016-11-29 00:23
@zapashcanon  yes, I am using Wayland.

**Comment by zapashcanon** [comment] 2016-11-29 12:17
I used to be on X, yesterday I started my session on Wayland and the extension didn't start. It never occurred on X. Can you reproduce it on X ?

**Comment by hslbck** [comment] 2016-12-01 16:24
@zapashcanon do you have media keys enabled on wayland? With disabled media keys I'm having no issue on wayland.

**Comment by zapashcanon** [comment] 2016-12-02 09:32
Yes, I guess they were enabled (I'll check soon). But, it wasn't a problem on X, so it's probably Wayland + media keys which cause the problem.

**Comment by jorgemf** [comment] 2016-12-03 00:51
@zapashcanon I have tested it today in Xorg, not issues. So I guess it is a wayland thing

**Comment by hslbck** [comment] 2016-12-05 18:21
Seems that `SettingsDaemon.MediaKeys` is not found when using wayland.
@zapashcanon do you use Archlinux?

**Comment by zapashcanon** [comment] 2016-12-05 18:37
No, I'm using Debian Unstable.

I just checked, Media Keys are enabled in the extensions prefs, is that what you wanted to know ?

**Comment by hslbck** [comment] 2016-12-05 18:50
OK, no I just wanted to know if this is an archlinux specific issue.

Until I have a fix for it the extension should work with wayland when you disable the media keys support in the prefs

**Comment by zapashcanon** [comment] 2016-12-05 19:06
Thanks. (I'm not using Wayland daily, I just noticed it the other day while trying something. ;) )

**Comment by zapashcanon** [comment] 2016-12-24 10:58
Yesterday, I did a lot of gnome-shell reload and computer reboot, and the problem occurred in Xorg one time. Media-keys were enabled and the extension didn't start. I'm not sure it's related, but it may mean that it's not Wayland related, but just happening less frequently in Xorg.

**Comment by hslbck** [comment] 2016-12-25 10:37
Did you have a look at the logs if `SettingsDaemon` was the cause of the problem as well?

On Wayland the extension gets loaded with MediaKeys enabled when the screen gets locked. It gets initialized in the lock screen, which should not happen. Afterwards the extension seems to work fine, but I can not check if media keys work.

**Comment by hslbck** [comment] 2017-01-12 22:51
Hi,

I changed the handling of media keys. The extension works for me on wayland when media key setting is enabled. But I can't tell if media keys itself are working, as I have none and xdotool doesn't work here ;) 
Can somebody verify the fix?

**Comment by jorgemf** [comment] 2017-01-12 23:26
@hslbck Media keys works only after disabling and enabling them. If you enable them, log out and log in again they don't work although the option appears as enabled.

**Comment by hslbck** [comment] 2017-01-15 16:01
ah ok for this issue I have to change the media key initialization after a logout.
In general the extension is working when you do a fresh start / reboot into wayland with media keys enabled?

**Comment by jorgemf** [comment] 2017-01-17 14:53
Yes, it is working fine, only that issue.

**Comment by bezcitu** [comment] 2017-01-24 09:00
I also have this issue with Internet Radio. After login, Internet Radio's icon isn't there and when I visit https://extensions.gnome.org/extension/836/internet-radio/, it shows "ERROR". Media keys are enabled, however they aren't working as long as gnome-shell isn't restarted.

After restarting gnome-shell (Alt + F2, "r"), the Internet Radio icon reappears, however when Arch is restarted, the icon isn't there again.

- Arch Linux (Kernel 4.8.13)
- GNOME Shell 3.22.2

**Comment by hslbck** [comment] 2017-01-31 15:14
@bezcitu Is this really the issue? What version of the extension do you use, the latest from github or the current version of the extension webpage.

The extension webpage version should not be affected by this issue using X.org. (If you can use `Alt + F2` you'r on X).
The latest Github version should work on a fresh. There is still a issue after a logout.

Can provide some logs?

**Comment by bezcitu** [comment] 2017-02-06 08:12
@hslbck 
Since yesterday I'm using the GitHub version. This may have fixed issue, since the icon is there when I log on to Arch/Gnome.
I was using the current version of the Gnome shell extension webpage.

**Comment by hslbck** [comment] 2017-02-16 00:01
@jorgemf Can you please try if media keys work after logout with the newest github version?

**Comment by jorgemf** [comment] 2017-02-18 15:06
@hslbck Not working for me yet

**Comment by hslbck** [comment] 2017-02-20 20:16
I see, media keys only work on wayland when the option gets reset. On X media keys should work after logging in again

**Comment by webmastak** [comment] 2017-10-31 13:24
Manjaro 17.0.6 Gellivara, X.org, multimedia keys not work in Gnome 3.26. With Gnome 3.24 worked.

**Closed** 2020-11-04 16:02 UTC
