### ISSUE TITLE
Crash on Ubuntu 17.10 (Wayland)

### ISSUE THREAD

**Issue by Svarozic** [hslbck/gnome-shell-extension-radio#75] opened 2017-10-15 09:13 UTC
Hi after I install this extension from https://extensions.gnome.org/extension/836/internet-radio/ my Ubuntu 17.10 (Wayland) freezes. My Gnome shell version is GNOME Shell 3.26.1.
I can not move with mouse and also keyboard stops to work. Restart and new login did not help, so I had to login with Xorg and uninstall this extension there to use Wayland. With Xorg it seems to work fine.

Installed extensions:
![screenshot from 2017-10-15 11-14-39](https://user-images.githubusercontent.com/3775835/31583345-31e7ffc0-b19a-11e7-94fe-46949ad972ab.png)

**Comment by hslbck** [comment] 2017-10-16 15:37
Hi,

I could reproduce the issue on Ubuntu 17.10 and Wayland without having any other extension installed. But I couldn't figure out the issue here yet. On Archlinux and Wayland the extension works fine. I'll keep looking.

**Comment by hyviquel** [comment] 2017-10-22 00:13
Got the same problem here

**Comment by junaru** [comment] 2017-10-28 11:37
Have you tried removing the gstreamer-vaapi package as mentioned in README.md? That solved it for me on Arch.

**Comment by hslbck** [comment] 2017-11-04 14:26
The issue is related to the gstreamer-vaapi package. It's installed by default on Ubuntu 17.10. After removing this package the extension works on Wayland and Ubuntu 17.10.

**Comment by hyviquel** [comment] 2017-11-04 15:01
is this a bug from gstreamer-vaapi that should be reported upstream?

**Comment by hslbck** [comment] 2017-11-06 18:41
I committed a branch gstreamer-vaapi, where the initalization of gstreamer has changed. Can someone please check, if the branch `gstreamer-vaapi` is working on Ubuntu 17.10 and Wayland. 
Archlinux and the gstreamer-vaapi installed works for me.

**Comment by Mamporrero** [comment] 2017-11-09 10:01
I've tried to install this on my Ubuntu 17.10 system with gstreamer1.0-vaapi installed. Under both Xorg and Wayland the result is the same: a red "ERROR" message. If I click on the blue configuration button (the only available option save for uninstalling) I get the following:

GLib.FileError: Failed to open file “/home/john/.local/share/gnome-shell/extensions/radio@hslbck.gmail.com/schemas/gschemas.compiled”: open() failed: No such file or directory

Stack trace:
  getSettings@/home/john/.local/share/gnome-shell/extensions/radio@hslbck.gmail.com/convenience.js:80:24
  RadioPrefsWidget<._init@/home/john/.local/share/gnome-shell/extensions/radio@hslbck.gmail.com/prefs.js:28:26
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  buildPrefsWidget@/home/john/.local/share/gnome-shell/extensions/radio@hslbck.gmail.com/prefs.js:117:18
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:246:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:402:5
  @<main>:1:43

**Comment by hslbck** [comment] 2017-11-10 15:43
@Mamporrero seems your installation was not successful, because the file "gschemas.compiled" is missing.

Tested the fix itself on Ubuntu 17.10 and Wayland with Ubuntu Session and Gnome Session and it works for both on my machine

**Comment by Mamporrero** [comment] 2017-11-10 18:09
On Fri, 10 Nov 2017, hslbck wrote:

> @Mamporrero seems your installation was not successful, because the file
> "gschemas.compiled" is missing.
> 
> Tested the fix itself on Ubuntu 17.10 and Wayland with Ubuntu Session and
> Gnome Session and it works for both on my machine

Release 7 installs and works for me on Ubuntu 17.10 using Xorg, but it crashes
Wayland (even with all other extensions disabled). Release 8 won’t install for
the same reason as previously (missing gschemas.compiled file). Please let me
know if there is any useful information (logs or whatever) that I could send
you.

John Smith (aka Mamporrero)

--
John Smith
jds10@cam.ac.uk
http://bombay.indology.info

**Comment by hslbck** [comment] 2017-11-11 07:31
ok, how did you install the extension from source? Did you run `make install`?
If this doesn't work can you try to compile the schema file by running the command `glib-compile-schemas` on the directory `schemas`

**Comment by Mamporrero** [comment] 2017-11-11 10:18
On Sat, 11 Nov 2017, hslbck wrote:

> ok, how did you install the extension from source?

Yes.

> Did you run make install?

I have done now. (Sorry, haven’t installed an extension from source before.)

Result (under Wayland): the extension installs and is visible on re-login.
However, clicking on it freezes Wayland again.

John aka Mamporrero

--
John Smith
jds10@cam.ac.uk
http://bombay.indology.info

**Comment by hslbck** [comment] 2017-11-11 11:07
Only for this extension you've to run `make install` on installation from source. For others it's probably different.

Do you run Ubuntu in a VM? I've seen the freezes in a VM as well, but not on real hardware.

**Comment by Mamporrero** [comment] 2017-11-11 13:23
On Sat, 11 Nov 2017, hslbck wrote:

> Do you run Ubuntu in a VM? I've seen the freezes in a VM as well, but not on
> real hardware.

No, it’s running natively on a real machine (a Dell Inspiron laptop). I’ve now
tried a second time with all other extensions disabled, but the same thing
happened: clicking on the extension showed me the previous station played, but
clicking on that crashed Wayland.

John aka Mamporrero

--
John Smith
jds10@cam.ac.uk
http://bombay.indology.info

**Comment by Zerrossetto** [comment] 2017-11-23 09:51
I confirm that this fixed the issue even for me but... what does `gstreamer-vaapi` package does? I'm afraid it may impact my everyday laptop use.

Also, I still not understand if is a `gstreamer-vaapi` bug or a radio indicator one.

**Comment by hslbck** [comment] 2017-11-23 14:54
This is probably a bug within `gstreamer-vaapi`, because other extensions are affected as well, see link in known issues. Further there are some entries in GNOME Bugzilla, e.g. https://bugzilla.gnome.org/show_bug.cgi?id=775698.

The branch `gstreamer-vaapi` has already been merged into master and a release has been published to extensions.gnome.org, which at least makes it possible to login for GNOME and Wayland with this extension active. But using the extension still crashes GNOME Shell sometimes

**Comment by thejacer87** [comment] 2017-12-13 04:18
confirmed crash on wayland, fine on xorg

lemme know if i can be of any help

**Comment by oyedotunsodiq045** [comment] 2018-05-17 05:32
REINSTALL GNOME SHELL

sudo apt install gnome-session

THE RESULT OF ABOVE WILL INSTALL LATEST GNOME ON UR DESKTOP

UPDATE AND UPGRADE

sudo apt-get update

sudo apt-get upgrade

CHECK GNOME VERSION

gnome-shell --version

RESULT SHOULD BE GNOME Shell 3.26.2

RESTART UR SYSTEM

FURTHER OPTION, NOT NECCESSARY THO, U CUD INTEGRATE UR FAVORITE BROWSER WTH GNOME TO WORK BETTER,FASTER AND EFFICIENTLY: SEE HELP LINK BELOW

https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome/Installation

**Comment by hslbck** [comment] 2018-05-24 16:54
great! Since Ubuntu switched back to X.Org by default for 18.04 I didn't start a Wayland session

**Closed** 2020-11-04 16:02 UTC
